### ISSUE TITLE
Not working..

### ISSUE THREAD

**Issue by simondevnet** [K4CZP3R/Ubisoft-Uplay-API-PHP#1]
Nice scripts, but:

PHP message: PHP Notice:  Undefined index: username in /var/www/uAPI.php on line 165
PHP message: PHP Notice:  Undefined index: userId in /var/www/uAPI.php on line 166
PHP message: PHP Notice:  Undefined index: ticket in /var/www/uAPI.php on line 168
PHP message: PHP Notice:  Undefined variable: uapi in /var/www/test.php on line 7
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function searchUser() on null in /var/www/test.php:7

**Comment by kacper-serewis** [comment]
Show me your test.php file

Op zondag 5 februari 2017 heeft DivisionHQde <notifications@github.com> het
volgende geschreven:

**Comment by simondevnet** [comment]
02:52:39 - [__construct ] - Using creds to login
02:52:39 - [generateB64Creds ] - B64: <catch>
02:52:39 - [begin refreshTicket ] - Checking if ubi gonna return normal answer
02:52:39 - [searchUser ] - Request URL: https://api-ubiservices.ubi.com/v2/profiles?nameOnPlatform=i7Simon&platformType=uplay
02:52:39 - [uplayticket ] - Returning Ticket
02:52:39 - [searchUser ] - Executed request (to see it, uncomment log line)
02:52:39 - [searchUser ] - 
02:52:39 - [searchUser ] - After making use of gzipdecode, string is empty, using orginal one...
02:52:39 - [refreshTicket ] - Ticket is still up-to-date
No Error: No action has been taken, ticket up-to-date

**Comment by kacper-serewis** [comment]
Show me content of your php file, not logs :) btw I dont see any errors in logs

**Comment by kacper-serewis** [comment]
Try using examples on main page of project

**Comment by kacper-serewis** [comment]
#2
