### ISSUE TITLE
unable to log in

### ISSUE THREAD

**Issue by spacerules** [K4CZP3R/Ubisoft-Uplay-API-PHP#2]
the output is 

`03:09:40 - [__construct ] - Using creds to login

03:09:40 - [generateB64Creds ] - B64: uncomment line below to see this

03:09:40 - [generateB64Creds ] - B64: <snap!>
03:09:40 - [login ] - Going to login...
03:09:40 - [login ] - 
url:https://connect.ubi.com/ubiservices/v2/profiles/sessions
appid:314d4fef-e568-454a-ae06-43e3bece12a6
authbasic:Y2hyaXN0b3BoZXJqYW1lc21vbnRnb21lcnlAZ21haWwuY29tOlBhc3N3b3JkMQ==
03:09:40 - [login ] - Executed request (to see it, uncomment log line)
03:09:40 - [login ] - After making use of g-zipdecode, string is empty, using orginal one...
03:09:40 - [login ] - Your authstring (to see it, uncomment next line of code)
03:09:40 - [login ] - Welcome, 
03:09:40 - [login ] - Your UserId is 
03:09:40 - [login ] - You can ignore last function for saving authstring but you'll need to edit some lines of codes to disable it
03:09:40 - [uplayticket ] - Returning Ticket
03:09:40 - [uplayticket ] - Saving ticket
03:09:40 - [uplayticket ] - Returning Ticket`

I can not get this to work. please take a look at my code and let me know what i am doing wrong.

[index.php.txt](https://github.com/K4CZP3R/Ubisoft-Uplay-API-PHP/files/801247/index.php.txt)
[uAPI.php.txt](https://github.com/K4CZP3R/Ubisoft-Uplay-API-PHP/files/801248/uAPI.php.txt)

please let me know if you 

please let me know how to fix this.

**Comment by kacper-serewis** [comment]
You can download new version of api and change login(); to login(2); to see error.

afaik ubi$it created anti-bot verification and logging in with this api isn't possible anymore
