### ISSUE TITLE
how do i make the captcha?

### ISSUE THREAD

**Issue by Lettly** [K4CZP3R/Ubisoft-Uplay-API-PHP#4]
Once I was blocked from accessing how do I do the chapcha?

>     [0] => {"message":"The Ubi-Challenge header is required."
>     [1] => "errorCode":1301
>     [2] => "httpCode":409
>     [3] => "errorContext":"Profiles Client Legacy"
>     [4] => "moreInfo":""
>     [5] => "transactionTime":"2017-10-15T19:40:09.1155351Z"

**Comment by kacper-serewis** [comment]
That's the problem, I don't have free time to make it working. Maybe in the future

**Comment by GitPotTime** [comment]
You could use proxies.
