### ISSUE TITLE
Adding more information about the game currenty played

### ISSUE THREAD

**Issue by ghost** [K4CZP3R/Ubisoft-Uplay-API-PHP#6]
So currently the API only supports info about what someone is playing atm. Not more detailed info about the game (you can see this info in the uplay client if you go to the friendlist E.G. Rainbow six supports that). It would be great to find the backend where ubisoft is gathering this info from.

**Comment by kacper-serewis** [comment]
Is the same info available on the ubisoft website?

**Comment by uniswapV1-V2** [comment]
有兴趣参加节点

**Comment by tiec7** [comment]
> 有兴趣参加节点

WHAT???
